sudo docker build -t india-agi-client . && \
CONTAINERS=$(sudo docker ps -q --filter "publish=4002") && \
[ -n "$CONTAINERS" ] && sudo docker stop $CONTAINERS || echo "No containers to stop" && \
sudo docker run -d -p 4002:4002 india-agi-client
